### ISSUE TITLE
插件能不能兼容一下旧版本的本地化部署？

### ISSUE THREAD

**Issue by kecikeci** [eolinker/EOLINKER-API-Studio-Plugins#12]
新版本的插件默认是服务器请求测试，但是本地内网部署的，服务器测试请求不到，导致链接超时，下边那几个问题单估计都是这问题。
虽然用5.0.4版本的插件可以，但是老是自动更新，很烦

能不能兼容一下？

**Comment by eolinker** [comment]
您好，开源版已经在2018年10月1日起停止维护，插件仅支持线上及付费的私有云产品。
