### ISSUE TITLE
edge 商店里没有对应插件

### ISSUE THREAD

**Issue by yangweijie** [eolinker/EOLINKER-API-Studio-Plugins#13]
最好发布一下， 主页里也留下链接

**Comment by eolinker** [comment]
目前插件仅支持 Chrome 和 Firefox 浏览器

**Comment by yangweijie** [comment]
> 目前插件仅支持 Chrome 和 Firefox 浏览器
edge浏览器也是chrome内核 每次下载离线插件 你们官方的升级了 用着用着请求不了 又不提示更新插件 很麻烦 客户端 体积又大

**Comment by scarqin** [comment]
@yangweijie 有空研究下，目前考虑到维护成本没有兼容，因为我们插件跟进 chrome worker，Firefox/Edge 跟进没那么快
