### ISSUE TITLE
插件问题, 不能使用

### ISSUE THREAD

**Issue by Cazaea** [eolinker/EOLINKER-API-Studio-Plugins#6]
我用Chrome, 通过扩展程序-->开发者模式 引入解压的3.5版本, 使用正常; 使用Chrome市场最新版, 无法调用接口, 请求超时, 无法得到回调, 是什么问题?

**Comment by eolinker** [comment]
您好，开源版已经在2018年10月1日起停止维护，插件仅支持线上及付费的私有云产品。
